### ISSUE TITLE
support configuring color scheme

### ISSUE THREAD

**Issue by radlinskii** [radlinskii/donkeytype#10]
Currently Colors are hardcoded (e.g. [here](https://github.com/radlinskii/donkeytype/blob/3e2b48cf547ef745a05bf891779a65705ea81623/src/runner.rs#L285)), which might make it not really accessible for some users. 
They work fine on my machine on light and dark mode, but that's only with my settings, and user should be able to adjust colors to her/his needs.

**Comment by kritikash18** [comment]
@radlinskii can I work on this issue if its available?

**Comment by radlinskii** [comment]
Yeah sure 👍

**Comment by kritikash18** [comment]
@radlinskii I've been trying out a few different things and needed some suggestions:
1. we currently use tui Color type which doesn't support fromStr so I'm able to set default color scheme but can't parse it from a string config file
2. further it doesn't implement serializable either so we can't directly de-serialize it from the file read object

so we can now either:
1. ask to add hex colors to config file and convert those hex to tui style color
2. use ratatui for colors since it supports parsing from string

what are your thoughts on this?

**Comment by kritikash18** [comment]
raised a PR with conversion to ratatui approach #18

**Comment by radlinskii** [comment]
Sorry I didn't reply sooner, I think replacing tui with ratatui might be a bit too much, and might require a lot of refactoring throughout the codebase. I think support only hex codes of colors would be enough.
I will put `hacktoberfest-accepted ` label on your pr anyway.

**Comment by kritikash18** [comment]
well I got a little excited when working on this and refactored the codebase to use ratatui anyway 🙂 so feel free to check it whenever you get some time; if it doesn't really suit the flow I'll add support for hex codes instead

**Comment by radlinskii** [comment]
You did a great job, thanks 👏
